package com.utam.simulation.config;

import io.micrometer.core.instrument.Gauge;
import io.micrometer.core.instrument.MeterRegistry;
import io.micrometer.core.instrument.Tag;
import io.micrometer.core.instrument.Tags;
import org.springframework.stereotype.Component;

import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.atomic.AtomicLong;

/**
 * Central registry for simulation metrics.
 * All generators register their metrics here for consistent naming and tagging.
 * 
 * Metrics exposed:
 * - simulation.records.total: Total records generated (by generator, entity type)
 * - simulation.records.rate: Records per second (by generator)
 * - simulation.errors.total: Total errors (by generator)
 * - simulation.generators.active: Number of active generators
 * - simulation.generators.status: Generator running status (gauge, 1=running, 0=stopped)
 */
@Component
public class SimulationMetrics {

    private final MeterRegistry meterRegistry;
    private final Map<String, AtomicLong> generatorCounts = new ConcurrentHashMap<>();
    private final Map<String, AtomicLong> generatorErrors = new ConcurrentHashMap<>();
    private final AtomicLong activeGenerators = new AtomicLong(0);

    public SimulationMetrics(MeterRegistry meterRegistry) {
        this.meterRegistry = meterRegistry;
        
        // Register gauge for active generators
        Gauge.builder("simulation.generators.active", activeGenerators, AtomicLong::get)
                .description("Number of active generators")
                .register(meterRegistry);
    }

    /**
     * Register a generator's status gauge.
     * 
     * @param generatorName Unique name of the generator
     * @param entityType Entity type produced by the generator
     * @param runningSupplier Supplier that returns true if generator is running
     */
    public void registerGeneratorStatus(String generatorName, String entityType, 
                                         java.util.function.Supplier<Boolean> runningSupplier) {
        Tags tags = Tags.of(
                Tag.of("generator", generatorName),
                Tag.of("entity_type", entityType)
        );

        Gauge.builder("simulation.generators.status", runningSupplier, s -> s.get() ? 1.0 : 0.0)
                .tags(tags)
                .description("Generator running status (1=running, 0=stopped)")
                .register(meterRegistry);

        // Initialize counters for this generator
        generatorCounts.put(generatorName, new AtomicLong(0));
        generatorErrors.put(generatorName, new AtomicLong(0));

        // Register gauge for records count
        Gauge.builder("simulation.records.total", generatorCounts.get(generatorName), AtomicLong::get)
                .tags(tags)
                .description("Total records generated")
                .register(meterRegistry);

        // Register gauge for errors count
        Gauge.builder("simulation.errors.total", generatorErrors.get(generatorName), AtomicLong::get)
                .tags(tags)
                .description("Total generation errors")
                .register(meterRegistry);
    }

    /**
     * Record records generated by a generator.
     */
    public void recordGenerated(String generatorName, long count) {
        AtomicLong counter = generatorCounts.get(generatorName);
        if (counter != null) {
            counter.addAndGet(count);
        }
    }

    /**
     * Record an error in a generator.
     */
    public void recordError(String generatorName) {
        AtomicLong counter = generatorErrors.get(generatorName);
        if (counter != null) {
            counter.incrementAndGet();
        }
    }

    /**
     * Increment active generators count.
     */
    public void generatorStarted() {
        activeGenerators.incrementAndGet();
    }

    /**
     * Decrement active generators count.
     */
    public void generatorStopped() {
        activeGenerators.decrementAndGet();
    }

    /**
     * Get the current count of active generators.
     */
    public long getActiveGeneratorsCount() {
        return activeGenerators.get();
    }

    /**
     * Get the total records generated by a specific generator.
     */
    public long getRecordsGenerated(String generatorName) {
        AtomicLong counter = generatorCounts.get(generatorName);
        return counter != null ? counter.get() : 0;
    }

    /**
     * Get the total errors for a specific generator.
     */
    public long getErrorCount(String generatorName) {
        AtomicLong counter = generatorErrors.get(generatorName);
        return counter != null ? counter.get() : 0;
    }

    /**
     * Reset all metrics (useful for testing).
     */
    public void reset() {
        activeGenerators.set(0);
        generatorCounts.values().forEach(c -> c.set(0));
        generatorErrors.values().forEach(c -> c.set(0));
    }
}
